'use strict';var Markdown={};
(function(){function l(n){return n}function x(){return!1}function p(){}function v(){}p.prototype={chain:function(n,q){var t=this[n];if(!t)throw Error("unknown hook "+n);this[n]=t===l?q:function(n){var h=Array.prototype.slice.call(arguments,0);h[0]=t.apply(null,h);return q.apply(null,h)}},set:function(n,q){if(!this[n])throw Error("unknown hook "+n);this[n]=q},addNoop:function(n){this[n]=l},addFalse:function(n){this[n]=x}};Markdown.HookCollection=p;v.prototype={set:function(n,q){this["s_"+n]=q},get:function(n){return this["s_"+
n]}};Markdown.Converter=function(){function n(a){return a=a.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?(?=\s|$)[ \t]*\n?[ \t]*((\n*)["(](.+?)[")][ \t]*)?(?:\n+)/gm,function(a,e,M,c,d,m){e=e.toLowerCase();G.set(e,b(M));if(d)return c;m&&H.set(e,m.replace(/"/g,"&quot;"));return""})}function q(a){a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,l);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math)\b[^\r]*?.*<\/\2>[ \t]*(?=\n+)\n)/gm,
l);a=a.replace(/\n[ ]{0,3}((<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,l);a=a.replace(/\n\n[ ]{0,3}(<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>[ \t]*(?=\n{2,}))/g,l);return a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,l)}function l(a,b){var e;e=b.replace(/^\n+/,"");e=e.replace(/\n+$/g,"");return e="\n\n~K"+(I.push(e)-1)+"K\n\n"}function x(a,b){a=z.preBlockGamut(a,L);a=C(a);a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?-[ ]?){3,}[ \t]*$/gm,
"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?_[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=k(a);a=E(a);a=d(a);a=z.postBlockGamut(a,L);a=q(a);return a=c(a,b)}function h(a){a=z.preSpanGamut(a);a=r(a);a=B(a);a=a.replace(/\\(\\)/g,A);a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,A);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,o);a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,o);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,y);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?((?:\([^)]*\)|[^()\s])*?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
y);a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,y);a=i(a);a=a.replace(/~P/g,"://");a=b(a);a=a.replace(/([\W_]|^)(\*\*|__)(?=\S)([^\r]*?\S[\*_]*)\2([\W_]|$)/g,"$1<strong>$3</strong>$4");a=a.replace(/([\W_]|^)(\*|_)(?=\S)([^\r\*_]*?\S)\2([\W_]|$)/g,"$1<em>$3</em>$4");a=a.replace(/  +\n/g," <br>\n");return a=z.postSpanGamut(a)}function B(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>)/gi,function(a){var b=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return b=
u(b,"!"==a.charAt(1)?"\\`*_/":"\\`*_")})}function y(a,b,e,c,d,g,i,A){void 0==A&&(A="");a=e.replace(/:\/\//g,"~P");c=c.toLowerCase();if(""==d)if(""==c&&(c=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=G.get(c))d=G.get(c),void 0!=H.get(c)&&(A=H.get(c));else if(-1<b.search(/\(\s*\)$/m))d="";else return b;d=m(d);d=u(d,"*_");b='<a href="'+d+'"';""!=A&&(A=j(A),A=u(A,"*_"),b+=' title="'+A+'"');return b+(">"+a+"</a>")}function j(a){return a.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}
function o(a,b,e,c,d,m,g,i){a=e;c=c.toLowerCase();i||(i="");if(""==d)if(""==c&&(c=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=G.get(c))d=G.get(c),void 0!=H.get(c)&&(i=H.get(c));else return b;a=u(j(a),"*_[]()");d=u(d,"*_");b='<img src="'+d+'" alt="'+a+'"';i=j(i);i=u(i,"*_");return b+(' title="'+i+'"')+" />"}function C(a){a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(a,b){return"<h1>"+h(b)+"</h1>\n\n"});a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,b){return"<h2>"+h(b)+"</h2>\n\n"});return a=
a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(a,b,e){a=b.length;return"<h"+a+">"+h(e)+"</h"+a+">\n\n"})}function k(a){var a=a+"~0",b=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;K?a=a.replace(b,function(a,b,e){a=-1<e.search(/[*+-]/g)?"ul":"ol";b=w(b,a);b=b.replace(/\s+$/,"");return"<"+a+">"+b+"</"+a+">\n"}):(b=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,a=a.replace(b,function(a,b,
e,c){a=-1<c.search(/[*+-]/g)?"ul":"ol";e=w(e,a);return b+"<"+a+">\n"+e+"</"+a+">\n"}));return a=a.replace(/~0/,"")}function w(a,b){K++;var a=a.replace(/\n{2,}$/,"\n"),e=N[b],c=!1,a=(a+"~0").replace(RegExp("(^[ \\t]*)("+e+")[ \\t]+([^\\r]+?(\\n+))(?=(~0|\\1("+e+")[ \\t]+))","gm"),function(a,b,e,d){a=d;(b=/\n\n$/.test(a))||-1<a.search(/\n{2,}/)||c?a=x(J(a),!0):(a=k(J(a)),a=a.replace(/\n$/,""),a=h(a));c=b;return"<li>"+a+"</li>\n"}),a=a.replace(/~0/g,"");K--;return a}function E(b){b=(b+"~0").replace(/(?:\n\n|^\n?)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(b,e,c){b=a(J(e));b=D(b);b=b.replace(/^\n+/g,"");b=b.replace(/\n+$/g,"");return"\n\n"+("<pre><code>"+b+"\n</code></pre>")+"\n\n"+c});return b=b.replace(/~0/,"")}function f(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(I.push(a)-1)+"K\n\n"}function r(b){return b=b.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(b,e,c,d){b=d.replace(/^([ \t]*)/g,"");b=b.replace(/[ \t]*$/g,"");b=a(b);b=b.replace(/:\/\//g,"~P");return e+"<code>"+b+"</code>"})}function a(a){a=a.replace(/&/g,"&amp;");
a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=u(a,"*_{}[]\\",!1)}function d(a){return a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,b){var e;e=b.replace(/^[ \t]*>[ \t]?/gm,"~0");e=e.replace(/~0/g,"");e=e.replace(/^[ \t]+$/gm,"");e=x(e);e=e.replace(/(^|\n)/g,"$1  ");e=e.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,b){var e;e=b.replace(/^  /mg,"~0");return e=e.replace(/~0/g,"")});return f("<blockquote>\n"+e+"\n</blockquote>")})}function c(a,b){for(var a=a.replace(/^\n+/g,
""),a=a.replace(/\n+$/g,""),e=a.split(/\n{2,}/g),c=[],d=/~K(\d+)K/,m=e.length,g=0;g<m;g++){var i=e[g];d.test(i)?c.push(i):/\S/.test(i)&&(i=h(i),i=i.replace(/^([ \t]*)/g,"<p>"),i+="</p>",c.push(i))}if(!b){m=c.length;for(g=0;g<m;g++)for(var u=!0;u;)u=!1,c[g]=c[g].replace(/~K(\d+)K/g,function(a,b){u=!0;return I[b]})}return c.join("\n\n")}function b(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?!]|~D)/gi,"&lt;")}function e(a,b,e,c){if(b)return a;if(")"!==
c.charAt(c.length-1))return"<"+e+c+">";for(var a=c.match(/[()]/g),d=b=0;d<a.length;d++)"("===a[d]?0>=b?b=1:b++:b--;var m="";0>b&&(c=c.replace(RegExp("\\){1,"+-b+"}$"),function(a){m=a;return""}));return"<"+e+c+">"+m}function i(a){a=a.replace(/(="|<)?\b(https?|ftp)(:\/\/[-A-Z0-9+&@#\/%?=~_|\[\]\(\)!:,\.;]*[-A-Z0-9+&@#\/%=~_|\[\])])(?=$|\W)/gi,e);return a=a.replace(/<((https?|ftp):[^'">\s]+)>/gi,function(a,b){return'<a href="'+b+'">'+z.plainLinkText(b)+"</a>"})}function g(a){return a=a.replace(/~E(\d+)E/g,
function(a,b){var e=parseInt(b);return String.fromCharCode(e)})}function J(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")}function D(a){if(!/\t/.test(a))return a;var b=["    ","   ","  "," "],e=0,c;return a.replace(/[\n\t]/g,function(a,d){if("\n"===a)return e=d+1,a;c=(d-e)%4;e=d+1;return b[c]})}function m(a){if(!a)return"";var b=a.length;return a.replace(F,function(e,c){return"~D"==e?"%24":":"==e&&(c==b-1||/[0-9\/]/.test(a.charAt(c+1)))?":":"%"+e.charCodeAt(0).toString(16)})}
function u(a,b,e){b="(["+b.replace(/([\[\]\\])/g,"\\$1")+"])";e&&(b="\\\\"+b);return a=a.replace(RegExp(b,"g"),A)}function A(a,b){return"~E"+b.charCodeAt(0)+"E"}var z=this.hooks=new p;z.addNoop("plainLinkText");z.addNoop("preConversion");z.addNoop("postNormalization");z.addNoop("preBlockGamut");z.addNoop("postBlockGamut");z.addNoop("preSpanGamut");z.addNoop("postSpanGamut");z.addNoop("postConversion");var G,H,I,K;this.makeHtml=function(a){if(G)throw Error("Recursive call to converter.makeHtml");G=
new v;H=new v;I=[];K=0;a=z.preConversion(a);a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a=D("\n\n"+a+"\n\n");a=a.replace(/^[ \t]+$/mg,"");a=z.postNormalization(a);a=q(a);a=n(a);a=x(a);a=g(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");a=z.postConversion(a);I=H=G=null;return a};var L=function(a){return x(a)},N={ol:"\\d+[.]",ul:"[*+-]"},F=/(?:["'*()[\]:]|~D)/g}})();
(function(){var l,x,p;function v(){}function n(a){this.buttonBar=k.getElementById("wmd-button-bar"+a);this.preview=k.getElementById("wmd-preview"+a);this.input=k.getElementById("wmd-input"+a)}function q(a,d){var c=this,b=[],e=0,i="none",g,f,D,m=function(a,b){i!=a&&(i=a,b||A());!l||"moving"!=i?f=setTimeout(u,1):D=null},u=function(a){D=new t(d,a);f=void 0};this.setCommandMode=function(){i="command";A();f=setTimeout(u,0)};this.canUndo=function(){return 1<e};this.canRedo=function(){return b[e+1]?!0:!1};
this.undo=function(){c.canUndo()&&(g?(g.restore(),g=null):(b[e]=new t(d),b[--e].restore(),a&&a()));i="none";d.input.focus();u()};this.redo=function(){c.canRedo()&&(b[++e].restore(),a&&a());i="none";d.input.focus();u()};var A=function(){var c=D||new t(d);if(!c)return!1;"moving"==i?g||(g=c):(g&&(b[e-1].text!=g.text&&(b[e++]=g),g=null),b[e++]=c,b[e+1]=null,a&&a())},z=function(a){var b=!1;if((a.ctrlKey||a.metaKey)&&!a.altKey)switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "y":c.redo();
b=!0;break;case "z":a.shiftKey?c.redo():c.undo(),b=!0}b&&(a.preventDefault&&a.preventDefault(),window.event&&(window.event.returnValue=!1))},k=function(a){!a.ctrlKey&&!a.metaKey&&(a=a.keyCode,33<=a&&40>=a||63232<=a&&63235>=a?m("moving"):8==a||46==a||127==a?m("deleting"):13==a?m("newlines"):27==a?m("escape"):(16>a||20<a)&&91!=a&&m("typing"))};(function(){j.addEvent(d.input,"keypress",function(a){(a.ctrlKey||a.metaKey)&&!a.altKey&&(89==a.keyCode||90==a.keyCode)&&a.preventDefault()});var a=function(){if((l||
D&&D.text!=d.input.value)&&void 0==f)i="paste",A(),u()};j.addEvent(d.input,"keydown",z);j.addEvent(d.input,"keydown",k);j.addEvent(d.input,"mousedown",function(){m("moving")});d.input.onpaste=a;d.input.ondrop=a})();u(!0);A()}function t(a,d){var c=this,b=a.input;this.init=function(){if(j.isVisible(b)&&(d||!(k.activeElement&&k.activeElement!==b)))if(this.setInputAreaSelectionStartEnd(),this.scrollTop=b.scrollTop,!this.text&&b.selectionStart||0===b.selectionStart)this.text=b.value};this.setInputAreaSelection=
function(){if(j.isVisible(b))if(void 0!==b.selectionStart&&!x)b.focus(),b.selectionStart=c.start,b.selectionEnd=c.end,b.scrollTop=c.scrollTop;else if(k.selection&&!(k.activeElement&&k.activeElement!==b)){b.focus();var a=b.createTextRange();a.moveStart("character",-b.value.length);a.moveEnd("character",-b.value.length);a.moveEnd("character",c.end);a.moveStart("character",c.start);a.select()}};this.setInputAreaSelectionStartEnd=function(){if(!a.ieCachedRange&&(b.selectionStart||0===b.selectionStart))c.start=
b.selectionStart,c.end=b.selectionEnd;else if(k.selection){c.text=j.fixEolChars(b.value);var e=a.ieCachedRange||k.selection.createRange(),d=j.fixEolChars(e.text),g="\u0007"+d+"\u0007";e.text=g;var f=j.fixEolChars(b.value);e.moveStart("character",-g.length);e.text=d;c.start=f.indexOf("\u0007");c.end=f.lastIndexOf("\u0007")-1;if(g=c.text.length-j.fixEolChars(b.value).length){for(e.moveStart("character",-d.length);g--;)d+="\n",c.end+=1;e.text=d}a.ieCachedRange&&(c.scrollTop=a.ieCachedScrollTop);a.ieCachedRange=
null;this.setInputAreaSelection()}};this.restore=function(){void 0!=c.text&&c.text!=b.value&&(b.value=c.text);this.setInputAreaSelection();b.scrollTop=c.scrollTop};this.getChunks=function(){var a=new v;a.before=j.fixEolChars(c.text.substring(0,c.start));a.startTag="";a.selection=j.fixEolChars(c.text.substring(c.start,c.end));a.endTag="";a.after=j.fixEolChars(c.text.substring(c.end));a.scrollTop=c.scrollTop;return a};this.setChunks=function(a){a.before+=a.startTag;a.after=a.endTag+a.after;this.start=
a.before.length;this.end=a.before.length+a.selection.length;this.text=a.before+a.selection+a.after;this.scrollTop=a.scrollTop};this.init()}function s(a,d,c){var b,e,i,g=function(){var a=0;window.innerHeight?a=window.pageYOffset:k.documentElement&&k.documentElement.scrollTop?a=k.documentElement.scrollTop:k.body&&(a=k.body.scrollTop);return a},f=function(){if(d.preview){var b=d.input.value;if(!(b&&b==i)){i=b;var c=(new Date).getTime(),b=a.makeHtml(b);e=(new Date).getTime()-c;r(b)}}},D=function(){b&&
(clearTimeout(b),b=void 0);var a=0,a=e;3E3<a&&(a=3E3);b=setTimeout(f,a)};this.refresh=function(a){a?(i="",f()):D()};this.processingTime=function(){return e};var m=!0,u=function(a){var b=d.preview,e=b.parentNode,c=b.nextSibling;e.removeChild(b);b.innerHTML=a;c?e.insertBefore(b,c):e.appendChild(b)},A=function(a){d.preview.innerHTML=a},z,G=function(a){if(z)return z(a);try{A(a),z=A}catch(b){z=u,z(a)}},r=function(a){var b=o.getTop(d.input)-g();d.preview&&(G(a),c());d.preview&&(d.preview.scrollTop=(d.preview.scrollHeight-
d.preview.clientHeight)*(d.preview.scrollHeight<=d.preview.clientHeight?1:d.preview.scrollTop/(d.preview.scrollHeight-d.preview.clientHeight)));if(m)m=!1;else{var e=o.getTop(d.input)-g();l?setTimeout(function(){window.scrollBy(0,e-b)},0):window.scrollBy(0,e-b)}};(function(a,b){j.addEvent(a,"input",b);a.onpaste=b;a.ondrop=b;j.addEvent(a,"keypress",b);j.addEvent(a,"keydown",b)})(d.input,D);f();d.preview&&(d.preview.scrollTop=0)}function h(a,d,c,b,e,i,g){var f,D,m,u,A,z,G,r,o,q,n,h;function F(a){y.focus();
if(a.textOp){c&&c.setCommandMode();var e=new t(d);if(!e)return;var m=e.getChunks(),g=function(){y.focus();m&&e.setChunks(m);e.restore();b.refresh()};a.textOp(m,g)||g()}a.execute&&a.execute(c)}function s(a,b){var e=a.getElementsByTagName("span")[0];b?(e.style.backgroundPosition=a.XShift+" 0px",a.onmouseover=function(){e.style.backgroundPosition=this.XShift+" -40px"},a.onmouseout=function(){e.style.backgroundPosition=this.XShift+" 0px"},l&&(a.onmousedown=function(){k.activeElement&&k.activeElement!==
d.input||(d.ieCachedRange=document.selection.createRange(),d.ieCachedScrollTop=d.input.scrollTop)}),a.isHelp||(a.onclick=function(){if(this.onmouseout)this.onmouseout();F(this);return!1})):(e.style.backgroundPosition=a.XShift+" -20px",a.onmouseover=a.onmouseout=a.onclick=function(){})}function p(a){"string"===typeof a&&(a=e[a]);return function(){a.apply(e,arguments)}}function v(){c&&(s(n,c.canUndo()),s(h,c.canRedo()))}var y=d.input;f=void 0;D=void 0;m=void 0;u=void 0;A=void 0;z=void 0;G=void 0;r=
void 0;o=void 0;q=void 0;n=void 0;h=void 0;(function(){var b=d.buttonBar,e=document.createElement("ul");e.id="wmd-button-row"+a;e.className="wmd-button-row";var e=b.appendChild(e),c=0,b=function(b,d,m,g){var i=document.createElement("li");i.className="wmd-button";i.style.left=c+"px";c+=25;var u=document.createElement("span");i.id=b+a;i.appendChild(u);i.title=d;i.XShift=m;g&&(i.textOp=g);s(i,!0);e.appendChild(i);return i},k=function(b){var d=document.createElement("li");d.className="wmd-spacer wmd-spacer"+
b;d.id="wmd-spacer"+b+a;e.appendChild(d);c+=25};f=b("wmd-bold-button",g("bold"),"0px",p("doBold"));D=b("wmd-italic-button",g("italic"),"-20px",p("doItalic"));k(1);m=b("wmd-link-button",g("link"),"-40px",p(function(a,b){return this.doLinkOrImage(a,b,!1)}));u=b("wmd-quote-button",g("quote"),"-60px",p("doBlockquote"));A=b("wmd-code-button",g("code"),"-80px",p("doCode"));z=b("wmd-image-button",g("image"),"-100px",p(function(a,b){return this.doLinkOrImage(a,b,!0)}));k(2);G=b("wmd-olist-button",g("olist"),
"-120px",p(function(a,b){this.doList(a,b,!0)}));r=b("wmd-ulist-button",g("ulist"),"-140px",p(function(a,b){this.doList(a,b,!1)}));o=b("wmd-heading-button",g("heading"),"-160px",p("doHeading"));q=b("wmd-hr-button",g("hr"),"-180px",p("doHorizontalRule"));k(3);n=b("wmd-undo-button",g("undo"),"-200px",null);n.execute=function(a){a&&a.undo()};k=/win/.test(E.platform.toLowerCase())?g("redo"):g("redomac");h=b("wmd-redo-button",k,"-220px",null);h.execute=function(a){a&&a.redo()};i&&(b=document.createElement("li"),
k=document.createElement("span"),b.appendChild(k),b.className="wmd-button wmd-help-button",b.id="wmd-help-button"+a,b.XShift="-240px",b.isHelp=!0,b.style.right="0px",b.title=g("help"),b.onclick=i.handler,s(b,!0),e.appendChild(b));v()})();var w="keydown";x&&(w="keypress");j.addEvent(y,w,function(a){if((a.ctrlKey||a.metaKey)&&!a.altKey&&!a.shiftKey){switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "b":F(f);break;case "i":F(D);break;case "l":F(m);break;case "q":F(u);break;case "k":F(A);
break;case "g":F(z);break;case "o":F(G);break;case "u":F(r);break;case "h":F(o);break;case "r":F(q);break;case "y":F(h);break;case "z":a.shiftKey?F(h):F(n);break;default:return}a.preventDefault&&a.preventDefault();window.event&&(window.event.returnValue=!1)}});j.addEvent(y,"keyup",function(a){if(a.shiftKey&&!a.ctrlKey&&!a.metaKey&&13===(a.charCode||a.keyCode))a={},a.textOp=p("doAutoindent"),F(a)});l&&j.addEvent(y,"keydown",function(a){if(27===a.keyCode)return!1});this.setUndoRedoButtonStates=v}function B(a,
d){this.hooks=a;this.getString=d}function y(a){return a.replace(/^\s*(.*?)(?:\s+"(.+)")?\s*$/,function(a,c,b){c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g," ")});c=decodeURIComponent(c);c=encodeURI(c).replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29");c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g,"%2b")});b&&(b=b.trim?b.trim():b.replace(/^\s*/,"").replace(/\s*$/,""),b=b.replace(/"/g,"quot;").replace(/\(/g,"&#40;").replace(/\)/g,"&#41;").replace(/</g,"&lt;").replace(/>/g,
"&gt;"));return b?c+' "'+b+'"':c})}var j={},o={},C={},k=window.document,w=window.RegExp,E=window.navigator;l=/msie/.test(E.userAgent.toLowerCase());p=/msie 6/.test(E.userAgent.toLowerCase())||/msie 5/.test(E.userAgent.toLowerCase());x=/opera/.test(E.userAgent.toLowerCase());var f={bold:"Strong <strong> Ctrl+B",boldexample:"strong text",italic:"Emphasis <em> Ctrl+I",italicexample:"emphasized text",link:"Hyperlink <a> Ctrl+L",linkdescription:"enter link description here",linkdialog:'<p><b>Insert Hyperlink</b></p><p>http://example.com/ "optional title"</p>',
quote:"Blockquote <blockquote> Ctrl+Q",quoteexample:"Blockquote",code:"Code Sample <pre><code> Ctrl+K",codeexample:"enter code here",image:"Image <img> Ctrl+G",imagedescription:"enter image description here",imagedialog:"<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",olist:"Numbered List <ol> Ctrl+O",ulist:"Bulleted List <ul> Ctrl+U",litem:"List item",
heading:"Heading <h1>/<h2> Ctrl+H",headingexample:"Heading",hr:"Horizontal Rule <hr> Ctrl+R",undo:"Undo - Ctrl+Z",redo:"Redo - Ctrl+Y",redomac:"Redo - Ctrl+Shift+Z",help:"Markdown Editing Help"};Markdown.Editor=function(a,d,c){c=c||{};"function"===typeof c.handler&&(c={helpButton:c});c.strings=c.strings||{};c.helpButton&&(c.strings.help=c.strings.help||c.helpButton.title);var b=function(a){return c.strings[a]||f[a]},d=d||"",e=this.hooks=new Markdown.HookCollection;e.addNoop("onPreviewRefresh");e.addNoop("postBlockquoteCreation");
e.addFalse("insertImageDialog");this.getConverter=function(){return a};var i=this,g;this.run=function(){if(!g){g=new n(d);var f=new B(e,b),D=new s(a,g,function(){e.onPreviewRefresh()}),m,u;/\?noundo/.test(k.location.href)||(m=new q(function(){D.refresh();u&&u.setUndoRedoButtonStates()},g),this.textOperation=function(a){m.setCommandMode();a();i.refreshPreview()});u=new h(d,g,m,D,f,c.helpButton,b);u.setUndoRedoButtonStates();(i.refreshPreview=function(){D.refresh(!0)})()}}};v.prototype.findTags=function(a,
d){var c=this,b;a&&(b=j.extendRegExp(a,"","$"),this.before=this.before.replace(b,function(a){c.startTag+=a;return""}),b=j.extendRegExp(a,"^",""),this.selection=this.selection.replace(b,function(a){c.startTag+=a;return""}));d&&(b=j.extendRegExp(d,"","$"),this.selection=this.selection.replace(b,function(a){c.endTag=a+c.endTag;return""}),b=j.extendRegExp(d,"^",""),this.after=this.after.replace(b,function(a){c.endTag=a+c.endTag;return""}))};v.prototype.trimWhitespace=function(a){var d,c=this;a?a=d="":
(a=function(a){c.before+=a;return""},d=function(a){c.after=a+c.after;return""});this.selection=this.selection.replace(/^(\s*)/,a).replace(/(\s*)$/,d)};v.prototype.skipLines=function(a,d,c){void 0===a&&(a=1);void 0===d&&(d=1);a++;d++;var b,e;navigator.userAgent.match(/Chrome/)&&"X".match(/()./);this.selection=this.selection.replace(/(^\n*)/,"");this.startTag+=w.$1;this.selection=this.selection.replace(/(\n*$)/,"");this.endTag+=w.$1;this.startTag=this.startTag.replace(/(^\n*)/,"");this.before+=w.$1;
this.endTag=this.endTag.replace(/(\n*$)/,"");this.after+=w.$1;if(this.before){for(b=e="";a--;)b+="\\n?",e+="\n";c&&(b="\\n*");this.before=this.before.replace(new w(b+"$",""),e)}if(this.after){for(b=e="";d--;)b+="\\n?",e+="\n";c&&(b="\\n*");this.after=this.after.replace(new w(b,""),e)}};j.isVisible=function(a){if(window.getComputedStyle)return"none"!==window.getComputedStyle(a,null).getPropertyValue("display");if(a.currentStyle)return"none"!==a.currentStyle.display};j.addEvent=function(a,d,c){a.attachEvent?
a.attachEvent("on"+d,c):a.addEventListener(d,c,!1)};j.removeEvent=function(a,d,c){a.detachEvent?a.detachEvent("on"+d,c):a.removeEventListener(d,c,!1)};j.fixEolChars=function(a){a=a.replace(/\r\n/g,"\n");return a=a.replace(/\r/g,"\n")};j.extendRegExp=function(a,d,c){if(null===d||void 0===d)d="";if(null===c||void 0===c)c="";var a=a.toString(),b,a=a.replace(/\/([gim]*)$/,function(a,c){b=c;return""}),a=a.replace(/(^\/|\/$)/g,"");return new w(d+a+c,b)};o.getTop=function(a,d){var c=a.offsetTop;if(!d)for(;a=
a.offsetParent;)c+=a.offsetTop;return c};o.getHeight=function(a){return a.offsetHeight||a.scrollHeight};o.getWidth=function(a){return a.offsetWidth||a.scrollWidth};o.getPageSize=function(){var a,d,c,b;self.innerHeight&&self.scrollMaxY?(a=k.body.scrollWidth,d=self.innerHeight+self.scrollMaxY):k.body.scrollHeight>k.body.offsetHeight?(a=k.body.scrollWidth,d=k.body.scrollHeight):(a=k.body.offsetWidth,d=k.body.offsetHeight);self.innerHeight?(c=self.innerWidth,b=self.innerHeight):k.documentElement&&k.documentElement.clientHeight?
(c=k.documentElement.clientWidth,b=k.documentElement.clientHeight):k.body&&(c=k.body.clientWidth,b=k.body.clientHeight);a=Math.max(a,c);d=Math.max(d,b);return[a,d,c,b]};C.createBackground=function(){var a=k.createElement("div"),d=a.style;a.className="wmd-prompt-background";d.position="absolute";d.top="0";d.zIndex="1000";l?d.filter="alpha(opacity=50)":d.opacity="0.5";var c=o.getPageSize();d.height=c[1]+"px";l?(d.left=k.documentElement.scrollLeft,d.width=k.documentElement.clientWidth):(d.left="0",d.width=
"100%");k.body.appendChild(a);return a};C.prompt=function(a,d,c){var b,e;void 0===d&&(d="");var i=function(a){27===(a.charCode||a.keyCode)&&g(!0)},g=function(a){j.removeEvent(k.body,"keydown",i);var d=e.value;a?d=null:(d=d.replace(/^http:\/\/(https?|ftp):\/\//,"$1://"),/^(?:https?|ftp):\/\//.test(d)||(d="http://"+d));b.parentNode.removeChild(b);c(d);return!1},f=function(){b=k.createElement("div");b.className="wmd-prompt-dialog";b.style.padding="10px;";b.style.position="fixed";b.style.width="400px";
b.style.zIndex="1001";var c=k.createElement("div");c.innerHTML=a;c.style.padding="5px";b.appendChild(c);var c=k.createElement("form"),m=c.style;c.onsubmit=function(){return g(!1)};m.padding="0";m.margin="0";m.cssFloat="left";m.width="100%";m.textAlign="center";m.position="relative";b.appendChild(c);e=k.createElement("input");e.type="text";e.value=d;m=e.style;m.display="block";m.width="80%";m.marginLeft=m.marginRight="auto";c.appendChild(e);var u=k.createElement("input");u.type="button";u.onclick=
function(){return g(!1)};u.value="OK";m=u.style;m.margin="10px";m.display="inline";m.width="7em";var f=k.createElement("input");f.type="button";f.onclick=function(){return g(!0)};f.value="Cancel";m=f.style;m.margin="10px";m.display="inline";m.width="7em";c.appendChild(u);c.appendChild(f);j.addEvent(k.body,"keydown",i);b.style.top="50%";b.style.left="50%";b.style.display="block";p&&(b.style.position="absolute",b.style.top=k.documentElement.scrollTop+200+"px",b.style.left="50%");k.body.appendChild(b);
b.style.marginTop=-(o.getHeight(b)/2)+"px";b.style.marginLeft=-(o.getWidth(b)/2)+"px"};setTimeout(function(){f();var a=d.length;if(void 0!==e.selectionStart)e.selectionStart=0,e.selectionEnd=a;else if(e.createTextRange){var b=e.createTextRange();b.collapse(!1);b.moveStart("character",-a);b.moveEnd("character",a);b.select()}e.focus()},0)};var r=B.prototype;r.prefixes="(?:\\s{4,}|\\s*>|\\s*-\\s+|\\s*\\d+\\.|=|\\+|-|_|\\*|#|\\s*\\[[^\n]]+\\]:)";r.unwrap=function(a){var d=new w("([^\\n])\\n(?!(\\n|"+
this.prefixes+"))","g");a.selection=a.selection.replace(d,"$1 $2")};r.wrap=function(a,d){this.unwrap(a);var c=new w("(.{1,"+d+"})( +|$\\n?)","gm"),b=this;a.selection=a.selection.replace(c,function(a,c){return(new w("^"+b.prefixes,"")).test(a)?a:c+"\n"});a.selection=a.selection.replace(/\s+$/,"")};r.doBold=function(a,d){return this.doBorI(a,d,2,this.getString("boldexample"))};r.doItalic=function(a,d){return this.doBorI(a,d,1,this.getString("italicexample"))};r.doBorI=function(a,d,c,b){a.trimWhitespace();
a.selection=a.selection.replace(/\n{2,}/g,"\n");var e=/(\**$)/.exec(a.before)[0],d=/(^\**)/.exec(a.after)[0],e=Math.min(e.length,d.length);e>=c&&(2!=e||1!=c)?(a.before=a.before.replace(w("[*]{"+c+"}$",""),""),a.after=a.after.replace(w("^[*]{"+c+"}",""),"")):!a.selection&&d?(a.after=a.after.replace(/^([*_]*)/,""),a.before=a.before.replace(/(\s?)$/,""),a.before=a.before+d+w.$1):(!a.selection&&!d&&(a.selection=b),c=1>=c?"*":"**",a.before+=c,a.after=c+a.after)};r.stripLinkDefs=function(a,d){return a=
a.replace(/^[ ]{0,3}\[(\d+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|$)/gm,function(a,b,e,i,g){d[b]=a.replace(/\s*$/,"");return i?(d[b]=a.replace(/["(](.+?)[")]$/,""),i+g):""})};r.addLinkDef=function(a,d){var c=0,b={};a.before=this.stripLinkDefs(a.before,b);a.selection=this.stripLinkDefs(a.selection,b);a.after=this.stripLinkDefs(a.after,b);var e="",i=/(\[)((?:\[[^\]]*\]|[^\[\]])*)(\][ ]?(?:\n[ ]*)?\[)(\d+)(\])/g,g=function(a){c++;a=a.replace(/^[ ]{0,3}\[(\d+)\]:/,
"  ["+c+"]:");e+="\n"+a},f=function(a,e,d,k,j,r){d=d.replace(i,f);return b[j]?(g(b[j]),e+d+k+c+r):a};a.before=a.before.replace(i,f);d?g(d):a.selection=a.selection.replace(i,f);var k=c;a.after=a.after.replace(i,f);a.after&&(a.after=a.after.replace(/\n*$/,""));a.after||(a.selection=a.selection.replace(/\n*$/,""));a.after+="\n\n"+e;return k};r.doLinkOrImage=function(a,d,c){a.trimWhitespace();a.findTags(/\s*!?\[/,/\][ ]?(?:\n[ ]*)?(\[.*?\])?/);var b;if(1<a.endTag.length&&0<a.startTag.length)a.startTag=
a.startTag.replace(/!?\[/,""),a.endTag="",this.addLinkDef(a,null);else if(a.selection=a.startTag+a.selection+a.endTag,a.startTag=a.endTag="",/\n\n/.test(a.selection))this.addLinkDef(a,null);else{var e=this,i=function(g){b.parentNode.removeChild(b);null!==g&&(a.selection=(" "+a.selection).replace(/([^\\](?:\\\\)*)(?=[[\]])/g,"$1\\").substr(1),g=" [999]: "+y(g),g=e.addLinkDef(a,g),a.startTag=c?"![":"[",a.endTag="]["+g+"]",a.selection||(a.selection=c?e.getString("imagedescription"):e.getString("linkdescription")));
d()};b=C.createBackground();c?this.hooks.insertImageDialog(i)||C.prompt(this.getString("imagedialog"),"http://",i):C.prompt(this.getString("linkdialog"),"http://",i);return!0}};r.doAutoindent=function(a){var d=!1;a.before=a.before.replace(/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ ]{0,3}>[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ \t]+\n$/,"\n\n");!a.selection&&!/^[ \t]*(?:\n|$)/.test(a.after)&&(a.after=a.after.replace(/^[^\n]*/,function(c){a.selection=
c;return""}),d=!0);/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]+.*\n$/.test(a.before)&&this.doList&&this.doList(a);/(\n|^)[ ]{0,3}>[ \t]+.*\n$/.test(a.before)&&this.doBlockquote&&this.doBlockquote(a);/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&this.doCode&&this.doCode(a);d&&(a.after=a.selection+a.after,a.selection="")};r.doBlockquote=function(a){a.selection=a.selection.replace(/^(\n*)([^\r]+?)(\n*)$/,function(b,c,e,d){a.before+=c;a.after=d+a.after;return e});a.before=a.before.replace(/(>[ \t]*)$/,function(b,
c){a.selection=c+a.selection;return""});a.selection=a.selection.replace(/^(\s|>)+$/,"");a.selection=a.selection||this.getString("quoteexample");var d="",c="",b;if(a.before){for(var e=a.before.replace(/\n$/,"").split("\n"),i=!1,g=0;g<e.length;g++){var f=!1;b=e[g];i=i&&0<b.length;/^>/.test(b)?(f=!0,!i&&1<b.length&&(i=!0)):f=/^[ \t]*$/.test(b)?!0:i;f?d+=b+"\n":(c+=d+b,d="\n")}/(^|\n)>/.test(d)||(c+=d,d="")}a.startTag=d;a.before=c;a.after&&(a.after=a.after.replace(/^\n?/,"\n"));a.after=a.after.replace(/^(((\n|^)(\n[ \t]*)*>(.+\n)*.*)+(\n[ \t]*)*)/,
function(b){a.endTag=b;return""});d=function(b){var c=b?"> ":"";a.startTag&&(a.startTag=a.startTag.replace(/\n((>|\s)*)\n$/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,c)+"\n"}));a.endTag&&(a.endTag=a.endTag.replace(/^\n((>|\s)*)\n/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,c)+"\n"}))};/^(?![ ]{0,3}>)/m.test(a.selection)?(this.wrap(a,70),a.selection=a.selection.replace(/^/gm,"> "),d(!0),a.skipLines()):(a.selection=a.selection.replace(/^[ ]{0,3}> ?/gm,""),this.unwrap(a),
d(!1),!/^(\n|^)[ ]{0,3}>/.test(a.selection)&&a.startTag&&(a.startTag=a.startTag.replace(/\n{0,2}$/,"\n\n")),!/(\n|^)[ ]{0,3}>.*$/.test(a.selection)&&a.endTag&&(a.endTag=a.endTag.replace(/^\n{0,2}/,"\n\n")));a.selection=this.hooks.postBlockquoteCreation(a.selection);/\n/.test(a.selection)||(a.selection=a.selection.replace(/^(> *)/,function(b,c){a.startTag+=c;return""}))};r.doCode=function(a){var d=/\S[ ]*$/.test(a.before);if(!/^[ ]*\S/.test(a.after)&&!d||/\n/.test(a.selection)){a.before=a.before.replace(/[ ]{4}$/,
function(b){a.selection=b+a.selection;return""});var c=d=1;/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&(d=0);/^\n(\t|[ ]{4,})/.test(a.after)&&(c=0);a.skipLines(d,c);a.selection?/^[ ]{0,3}\S/m.test(a.selection)?/\n/.test(a.selection)?a.selection=a.selection.replace(/^/gm,"    "):a.before+="    ":a.selection=a.selection.replace(/^(?:[ ]{4}|[ ]{0,3}\t)/gm,""):(a.startTag="    ",a.selection=this.getString("codeexample"))}else a.trimWhitespace(),a.findTags(/`/,/`/),!a.startTag&&!a.endTag?(a.startTag=a.endTag=
"`",a.selection||(a.selection=this.getString("codeexample"))):a.endTag&&!a.startTag?(a.before+=a.endTag,a.endTag=""):a.startTag=a.endTag=""};r.doList=function(a,d,c){var d=/^\n*(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*/,b="-",e=1,i=function(){var a;c?(a=" "+e+". ",e++):a=" "+b+" ";return a},g=function(a){void 0===c&&(c=/^\s*\d/.test(a));return a=a.replace(/^[ ]{0,3}([*+-]|\d+[.])\s/gm,function(){return i()})};a.findTags(/(\n|^)*[ ]{0,3}([*+-]|\d+[.])\s+/,
null);a.before&&!/\n$/.test(a.before)&&!/^\n/.test(a.startTag)&&(a.before+=a.startTag,a.startTag="");if(a.startTag){var f=/\d+[.]/.test(a.startTag);a.startTag="";a.selection=a.selection.replace(/\n[ ]{4}/g,"\n");this.unwrap(a);a.skipLines();f&&(a.after=a.after.replace(d,g));if(c==f)return}var k=1;a.before=a.before.replace(/(\n|^)(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*$/,function(a){/^\s*([*+-])/.test(a)&&(b=w.$1);k=/[^\n]\n\n[^\n]/.test(a)?1:0;
return g(a)});a.selection||(a.selection=this.getString("litem"));var f=i(),m=1;a.after=a.after.replace(d,function(a){m=/[^\n]\n\n[^\n]/.test(a)?1:0;return g(a)});a.trimWhitespace(!0);a.skipLines(k,m,!0);a.startTag=f;d=f.replace(/./g," ");this.wrap(a,72-d.length);a.selection=a.selection.replace(/\n/g,"\n"+d)};r.doHeading=function(a){a.selection=a.selection.replace(/\s+/g," ");a.selection=a.selection.replace(/(^\s+|\s+$)/g,"");if(a.selection){var d=0;a.findTags(/#+[ ]*/,/[ ]*#+/);/#+/.test(a.startTag)&&
(d=w.lastMatch.length);a.startTag=a.endTag="";a.findTags(null,/\s?(-+|=+)/);/=+/.test(a.endTag)&&(d=1);/-+/.test(a.endTag)&&(d=2);a.startTag=a.endTag="";a.skipLines(1,1);d=0==d?2:d-1;if(0<d){var d=2<=d?"-":"=",c=a.selection.length;72<c&&(c=72);for(a.endTag="\n";c--;)a.endTag+=d}}else a.startTag="## ",a.selection=this.getString("headingexample"),a.endTag=" ##"};r.doHorizontalRule=function(a){a.startTag="----------\n";a.selection="";a.skipLines(2,1,!0)}})();
(function(){function l(){for(var a=0;a<w.length;a++)w[a].refreshPreview()}function x(a){var b=a.match(/^\s*>\s*!/mg);if(b&&b.length==a.split("\n").length){var c=!1,a=a.replace(/(.*) (\w)/,function(a,b,e){c=!0;return b+"\n> "+e});c||(a=a.replace(/^(\s*>\s*)!/m,"$1&#33;"))}return a}function p(a){var b=/^\s*?[^\s!]/m,c=/^\s*?!/gm;return a=a.replace(/\<blockquote\>[\n\s]*?\<p\>[\n\s]*?(![\s\S]*?)\<\/p\>[\n\s]*?\<\/blockquote\>/g,function(a,e){if(b.test(e))return a;a=a.replace(e,e.replace(c,""));return a=
a.replace("<blockquote>",'<blockquote class="spoiler">')})}function v(a){if(!window.tagRendererRaw)return a;var b,c;return a=a.replace(/\[(meta-)?tag:([a-z0-9#+.-]+)\]/gi,function(e,d,g,i){if(!k&&d)return e;if(!b){for(var f=a,j=[],r=/<(a|code)[^>]*>/ig,h;null!=(h=r.exec(f));){j.push(h.index);h=RegExp("</"+h[1]+">","ig");h.lastIndex=r.lastIndex;if(null==h.exec(f))break;j.push(h.lastIndex);r.lastIndex=h.lastIndex}b=j;c=b.length}f=!1;for(j=0;j<c&&!(b[j]>i);j++)f=!f;if(f)return e;e=null;k&&!d&&(e=C);
return tagRendererRaw(sanitizeAndSplitTags(g)[0],e)})}function n(a){var b,c;"undefined"==typeof r&&(r=StackExchange.options.styleCode);r&&(b=h(a),c=h(b+a),a=y(a,b,c));a=q(a);r&&(a=j(a,b,c));return a}function q(a){return a.replace(/<[^>]*>?/gi,t)}function t(b){return b.match(a)||b.match(d)||b.match(c)?b:""}function s(a){if(""==a)return"";var b=/<\/?\w+[^>]*(\s|$|>)/g,c=a.toLowerCase().match(b),e=(c||[]).length;if(0==e)return a;for(var d,g,i,f=[],k=[],j=!1,h=0;h<e;h++)if(d=c[h].replace(/<\/?(\w+).*/,
"$1"),!(f[h]||-1<"<p><img><br><li><hr>".search("<"+d+">"))){g=c[h];i=-1;if(!/^<\//.test(g))for(g=h+1;g<e;g++)if(!f[g]&&c[g]=="</"+d+">"){i=g;break}-1==i?j=k[h]=!0:f[i]=!0}if(!j)return a;h=0;return a=a.replace(b,function(a){a=k[h]?"":a;h++;return a})}function h(a){a=(a.match(/~/g)||[]).length;return Array(a+2).join("~")}function B(a){if(/^lang-/.test(a))return a;var c="c_"+a,d=b[c];if(d)return d;if(e[c])return null;e[c]=!0;c=i.length;0<c&&RegExp("^"+i[c-1]).test(a)?i[c-1]=a:i.push(a);g.trigger();return null}
function y(a,b,c){a=a.replace(J,function(a,c,e){return b+c+b+e});return a.replace(D,function(a,b){return c+b+c})}function j(a,b,c){var a=a.replace(RegExp(b+"([a-z0-9#+.-]+)"+b+"(\\s*?<pre)","gi"),function(a,b,c){a=B(b);return!a?c:c+" class='"+a+" prettyprint-override'"}),e;return a.replace(RegExp("("+c+"([a-z0-9#+.-]+)"+c+")|(<pre><code>)","gi"),function(a,b,c){if(b)return e=c,"";if(!e)return a;b=B(e);return!b?a:"<pre class='"+b+" prettyprint-override'><code>"})}function o(a){function b(){d.animate({height:g.height()-
i})}function c(a){if(g)a();else if(!j){j=!0;var e=r.offset();i=e.top-$("#wmd-button-row"+h).offset().top-$("#wmd-button-row"+h).outerHeight()-5;f=$("#wmd-help-button"+h);var m=f.offset().left+f.outerWidth(),e=e.left,o=r.outerWidth()+e,o=Math.max(m,o);k={right:m-o,width:o-e,top:$("#wmd-button-row"+h).outerHeight()+5};f.addClass("active-help");d=$("<div style='clear:both' />").insertBefore(r);g=$('<div id="mdhelp'+h+'" class="mdhelp"><ul id="mdhelp-tabs'+h+'" class="mdhelp-tabs"><li /></ul></div>').find("li").addSpinner().end().css(k).insertAfter(f);
b();$.get("/posts/markdown-help",{postfix:h}).done(function(c){g.remove();g=$(c).insertAfter(f).css(k);$("#mdhelp-tabs"+h).delegate("li:not(:last-child)","click",function(){var a=$(this).hasClass("selected");g.find(".mdhelp-tab").hide();$("#mdhelp-tabs"+h+" li").removeClass("selected");if(!a&&($("#"+$(this).attr("data-tab")).show(),$(this).addClass("selected"),a=$(this).attr("data-buttons")))for(var a=a.split(","),c=0;c<a.length;c++){var e=$("#wmd-"+a[c]+"-button"+h);e.is(":animated")||e.animate({top:-15},
400).animate({top:0},400).animate({top:-8},300).animate({top:0},300).animate({top:-4},200).animate({top:0},200).animate({top:-2},100).animate({top:0},100).animate({top:-1},50).animate({top:0},50)}b()});j=!1;a()})}}function e(){o=!0;c(function(){f.addClass("active-help");g.show();b()})}var d,g,i,f,k,j=!1,h=(a||{}).postfix||"",r=$("#wmd-input"+h),o=!1;this.toggle=function(){g&&g.is(":visible")?(g.hide(),d.animate({height:0}),f.removeClass("active-help")):e()};this.showOnce=function(){o||e()}}if(!StackExchange.MarkdownEditor){var C,
k,w=[],E=function(a){function b(a){return"facebook.stackoverflow.com"===a?"stackoverflow.com":a}function c(b){window.apiCallbacks[b]||(window.apiCallbacks[b]=function(c){if(c)if(c.error_message)/^No site found/.test(c.error_message)&&(r["s_"+b]=!0);else if(c.items){for(var c=c.items,e=c.length,d=0;d<e;d++){var g=c[d];f[b+"|"+g.question_id]=g.title}a&&a()}});return'apiCallbacks["'+b+'"]'}function e(a,c){if(b(a)===i)return!0;var d=o[a];d||(d=o[a]={count:0,ids:{}});if(d.ids[c])return!0;if(d.count>=n)return!1;
d.count++;return d.ids[c]=!0}var d=/<a href="((\S+)\/q(?:uestions)?\/(\d+)(?:|\/\S*?))">\1<\/a>/g,g=window.location.hostname.toLowerCase(),i=b(g),f={},k={},h={},j=StackExchange.helpers.DelayedReaction(function(){var a=!1,e;for(e in h)if(h.hasOwnProperty(e)){var d=c(e),g;30<h[e].length?g=h[e].splice(0,30).join(";"):(g=h[e].join(";"),delete h[e]);a=!0;$.ajax({url:"http://api.stackexchange.com/2.0/questions/"+g+"?pagesize=30&key=6AU78DZ)GcdjNjAszYmTLQ((&filter=!6G7RPxWUNTleV&site="+b(e),crossDomain:!0,
jsonpCallback:d,dataType:"jsonp"});break}a&&j.trigger()},1E3,{sliding:!0}),r={};window.apiCallbacks={};var o={},n=/^meta\./.test(i)?40:10;return function(a){o={};return a.replace(d,function(a,c,d,g){d=d.toLowerCase().replace(/^http:\/\//,"");if(/[^a-z0-9.]/.test(d)||!e(d,g))return a;var m=f[d+"|"+g];if(m)g=m;else{if(m=!k[d+"|"+g]){m=b(d);if(m===i)m=!1;else if(r["s_"+m])m=!0;else var o=/^meta\./.test(i),m=i==="meta."+m||!o&&"meta."+i===m||o&&"meta.stackoverflow.com"==m||"meta.stackoverflow.com"===
i?!1:!0;m=!m}m&&(k[d+"|"+g]=!0,(m=h[d])||(m=h[d]=[]),m.push(g),j.trigger());g=null}return!g?a:'<a href="'+c+'">'+g+"</a>"})}}(l),f=$.Callbacks();StackExchange.MarkdownEditor=function(a){var b=a.postfix||"";C=$("#hlinks a").filter(function(){return"main"==$(this).text()}).attr("href");k=!!C;var c=new Markdown.Converter,e=c.hooks;e.addNoop("preSafe");e.chain("postConversion",E);e.chain("postConversion",function(a){return e.preSafe(a)});e.chain("postConversion",n);e.chain("postConversion",s);e.chain("postConversion",
p);e.chain("postConversion",v);var d=new o({postfix:b}),g={helpButton:{handler:d.toggle}};a.noCode&&(g.strings={code:"Preformatted text <pre><code> Ctrl-K",codeexample:"enter preformatted text here"});c=new Markdown.Editor(c,b,g);c.hooks.chain("postBlockquoteCreation",x);StackExchange.options.disableImageUploads||c.hooks.set("insertImageDialog",StackExchange.imageUploader.uploadImageDialog);f.fire(c,a.postfix);var i=$("#wmd-preview"+b);c.hooks.chain("onPreviewRefresh",function(){i.trigger("wmdrefresh")});
w.push(c);c.run();if(a.immediatelyShowMarkdownHelp)d.showOnce(a);else if(a.autoShowMarkdownHelp)$("#wmd-input"+b).one("focus",function(){d.showOnce(a)});c.disableSubmission=function(){$("#submit-button"+b).attr("disabled","disabled");StackExchange.navPrevention.stop()};return c};StackExchange.MarkdownEditor.creationCallbacks=f;StackExchange.MarkdownEditor.refreshAllPreviews=l;var r;StackExchange.MarkdownEditor.sanitizeHtml=q;var a=/^(<\/?(b|blockquote|code|del|dd|dl|dt|em|h1|h2|h3|i|kbd|li|ol|p|pre|s|sup|sub|strong|strike|ul)>|<(br|hr)\s?\/?>)$/i,
d=/^(<a\shref="((https?|ftp):\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\stitle="[^"<>]+")?\s?>|<\/a>)$/i,c=/^(<img\ssrc="(https?:\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\swidth="\d{1,3}")?(\sheight="\d{1,3}")?(\salt="[^"<>]*")?(\stitle="[^"<>]*")?\s?\/?>)$/i;StackExchange.MarkdownEditor.balanceTags=s;var b={},e={},i=[],g=StackExchange.helpers.DelayedReaction(function(){0!=i.length&&($.ajax("/api/tags/"+encodeURIComponent(i.join(";"))+"/syntax-highlight",{cache:!0}).done(function(a){var c=!1,
e;for(e in a)a.hasOwnProperty(e)&&(b["c_"+e]=a[e],c=!0);c&&(StackExchange.MarkdownEditor.refreshAllPreviews(),styleCode())}),i=[])},2E3,{sliding:!0}),J=/<\!-- language: ([a-z0-9#+\-.]+) --\>(\s*?<pre>\s*?<code>)/gi,D=/<\!-- language-all: ([a-z0-9#+\-.]+) --\>/gi}})();
StackExchange.editor=function(){var l=function(l){var l=l||{},p=l.postfix||"",v=l.heartbeatType,n=l.bindNavPrevention,q=$("#post-form"+p),t=$("#wmd-input"+p),s;s=$("#title, #edit-comment, #m-address, .edit-comment");p=s.add(".tag-editor input");q.submit(function(){s.each(function(){StackExchange.helpers.hideHelpOverlay($(this))});StackExchange.helpers.disableSubmitButton(q);StackExchange.navPrevention.stop();return!0});$(".original-question").not(".processed").TextAreaResizer();t.not(".processed").TextAreaResizer();
t.typeWatch({highlight:!1,wait:5E3,captureLength:5,callback:styleCode});var h=new StackExchange.MarkdownEditor(l);if(v){var B=l.discardSelector?$(l.discardSelector):null;StackExchange.cardiologist.addHeart(v,t,h,B,l.postId)}if("ask"==v||"answer"==v){var y=t.add(p),j=function(){StackExchange.helpers.loadTicks(q);y.unbind("keydown",j);return!0};y.bind("keydown",j)}n&&StackExchange.navPrevention.init(t);q.find(".wmd-preview").click(function(){$(this).siblings().find("textarea").focus()});StackExchange.helpers.bindHelpOverlayEvents(s);
0==$("#ask-page-has-errors").length&&$("#title").is("input")&&$("#title").focus();if(l.oncreated)l.oncreated(h);if(l.discardSelector&&("ask"==v||"answer"==v)){var o=$(l.discardSelector);o.click(function(j){j.preventDefault();confirm("Are you sure you want to discard your draft?")&&($("#title").val("").blur(),$("#question-suggestions").empty(),$("#wmd-input-42").val(""),$("#wmd-preview-42").html(""),$("#answer-from-ask").is(":visible")&&$("#answer-from-ask").is(":checked")&&$("#answer-from-ask").click(),
j=$("#tagnames"),0<j.length&&j[0].func_clear&&(j[0].func_clear(),j.blur()),t.val("").blur(),h.refreshPreview(),$.post("/post/discard-draft",{fkey:StackExchange.options.user.fkey,postType:v},function(){$("#draft-saved").hide();$("#draft-discarded").show();var h=null,h=function(){$("#draft-discarded").hide();$("#title").unbind("keypress",h);t.unbind("keypress",h)};$("#title").bind("keypress",h);t.bind("keypress",h)}),o.hide())})}};return{init:l,initIfShown:function(x){var p=(x||{}).postfix||"";0!=$("#wmd-preview"+
p).length&&("-42"!==p||0===$("#answer-from-ask").length)&&0===$("#show-editor-button"+p).length?(l(x),StackExchange.editor.finallyInit||(StackExchange.editor.finallyInit=function(){})):StackExchange.editor.finallyInit=function(){l(x)}}}}();
StackExchange.cardiologist=function(){function l(f){f="number"===typeof f?f:1E3*(B+y);C&&(f=Math.max(f,6E3-((new Date).getTime()-C)));k&&clearTimeout(k);k=setTimeout(x,f)}function x(){k=null;if(!t.length){var f;t=[];q&&!q.isDisabled&&30>q.beatCount&&t.push(q);for(var h=0;h<n.length;h++)f=n[h],f!=q&&!f.isDisabled&&30>f.beatCount&&t.push(f);B=Math.max(15,Math.min(45,60/(t.length||1)))}t.length?(f=t.shift(),f.checkActive()?f.beat():l()):l()}function p(){}function v(f){var h=[];$.get("/questions/"+f,
function(a){a=$(a);a.find("div.answer").each(function(){var a=this.id.substring(7);0==$("#answer-"+a).length&&h.push(this.id)});if(0<h.length){var d="#"+h.join(",#"),a=a.find(d),d=$("div.answer:last");0==d.length&&(d=$("#answers-header"));a.hide();d.after(a);a.fadeIn("slow");d=$("div.answer").length;$(".subheader h2").text(d+" Answer"+(1<d?"s":""));StackExchange.vote.init(f);StackExchange.comments.init({post:a})}StackExchange.notify.close(o);j=!1},"html")}var n=[],q,t=[],s,h,B=45,y=0,j=!1,o=-2,C,
k,w={ask:function(f){if(f.relatedQuestions){var j=$("#how-to-format"),a=f.relatedQuestions!=h;a&&j.hide();j.empty().append("<h4>Similar Questions</h4>"+f.relatedQuestions);a&&showFadingHelpText(j);h=f.relatedQuestions}f.suggestedTags&&StackExchange.tagSuggestions&&StackExchange.tagSuggestions.suggest(f.suggestedTags)},answer:function(f,h){if(f&&!j)if(f.disableEditor)StackExchange.notify.show("This question has been "+f.message+" - no more answers will be accepted.",o),j=!0;else{var a=parseInt(f.message);
0<a&&(StackExchange.notify.show(a+" new answer"+(1==a?" has":"s have")+' been posted - <a id="load-new-answers">load new answers.</a>',o),j=!0,$("#load-new-answers").click(function(){v(h.postId)}))}},edit:function(f){f&&f.message&&StackExchange.notify.getMessageText(o)!=$("<span />").html(f.message).text()&&(StackExchange.notify.close(o),StackExchange.notify.show(f.message,o))}};p.prototype={activate:function(){q=this;this.isActive||(this.isActive=!0,this.beatCount=0,n.push(this),1===n.length&&l())},
checkActive:function(){if(!this.isActive||this.isDisabled)return!1;return!this.jTextarea.closest("body").length?(delete this.jTextarea,this.isDisabled=!0,!1):!0},beat:function(f){var h=this,a={type:"POST",url:"/posts/"+this.postId+"/editor-heartbeat/"+this.type,dataType:"json",data:{}};f||(a.success=function(a){h.success(a)},a.error=function(){h.error()},a.complete=function(){h.complete()});if(this.shouldSendDraft()){var d={text:this.jTextarea.val()};"ask"===this.type&&(d.title=$("#title").val(),
d.tagnames=$("#tagnames").val(),d.answertext=$("#wmd-input-42").val());if(!s||s.heart!==this||s.title!==d.title||s.tagnames!==d.tagnames||s.text!==d.text||s.answertext!==d.answertext)a.data=d,s={heart:this,title:d.title,tagnames:d.tagnames,text:d.text,answertext:d.answertext}}if(f&&!("text"in a.data))return $.Deferred().resolve().promise();this.revisionGuid&&(a.data.clientRevisionGuid=this.revisionGuid);"answer"===this.type&&(f=$("#answers-header .answers-subheader h2").text().replace(/ answers?/i,
"")||"0",a.data.clientCount=f);C=(new Date).getTime();return $.ajax(a).promise()},shouldSendDraft:function(){return"edit"!==this.type&&q===this},success:function(f){w[this.type](f,this);f.disableEditor&&(this.editor.disableSubmission(),this.isDisabled=!0);f.draftSaved&&E(this.jTextarea,this.discardDraftLink);this.beatCount++;y=0},error:function(){$("#draft-saved").hide();q===this&&t.unshift(this);y=(new Date).getTime()%100/10},complete:function(){l()}};var E=function(f,h){var a=$("#draft-saved"),
d=function(){a.text("draft saved").fadeIn("fast")};a.is(":visible")?a.fadeOut("fast",d):d();h&&h.removeClass("dno").show();var c=function(a){if(115!=a.which||!a.ctrlKey||a.shiftKey||a.altKey)f.unbind("keypress",c),$("#draft-saved").fadeOut("fast")};f.bind("keypress",c);$("#draft-discarded").hide()};return{addHeart:function(f,h,a,d,c){var b=new p,e;b.type=f;b.jTextarea=h;b.discardDraftLink=d;switch(f){case "ask":e=0;break;case "answer":e=$("#post-id").val()||location.href.match(/\/questions\/(\d+)/i)[1];
break;case "edit":e=c||$("#post-id").val()||h.closest(".question, .answer").find(".vote input").val(),f=h.closest(".inline-post"),d=null,0<f.length&&(d=f[0].action.split("/").pop()),d||(d=$("#client-revision-guid").val()),b.revisionGuid=d}b.postId=e;b.editor=a;h.keypress(function(){b.activate()})},ensureDraftSaved:function(f,h){!q||!q.checkActive()?f():q.beat(h).done(f)},beatASAP:function(){l(1)},notifiedOfNewAnswer:function(){j=!0},isHeartBeating:function(){if(null==n)return!1;for(var f=0;f<n.length;f++)if(!0==
n[f].checkActive())return!0;return!1}}}();
StackExchange.navPrevention=function(){var l,x,p=function(){var n=!1;l.each(function(l){n=n||$(this).val()!==x[l]});return n},v=function(n){window.onbeforeunload=n?function(){if(l&&p())return n}:null},n=function(){v("You have started writing or editing a post.")};return{init:function(q){l=q.one("keypress",n);x=[];q.each(function(){x.push($(this).val())})},start:function(){l&&n()},stop:function(){l&&(l.unbind("keypress",n),v(null),l=null)},confirm:function(n){return l&&p()?confirm(n):!0}}}();
(function(l){function x(h){n=l(h.data.el);n.blur();t=h.clientY+document.documentElement.scrollTop;q=n.height()-t;n.css("opacity",0.25);l(document).mousemove(p).mouseup(v);return!1}function p(h){var l=h.clientY+document.documentElement.scrollTop,p=q+l;t>=l&&(p-=5);t=l;p=Math.max(s,p);n.height(p+"px");p<s&&v(h);return!1}function v(){l(document).unbind("mousemove",p).unbind("mouseup",v);n.css("opacity",1);n.focus();q=n=null;t=0}var n,q,t=0,s=32;l.fn.TextAreaResizer=function(){return this.each(function(){n=
l(this).addClass("processed");q=null;l(this).parent().append(l('<div class="grippie"></div>').bind("mousedown",{el:this},x));var h=l("div.grippie",l(this).parent())[0];h.style.marginRight=h.offsetWidth-l(this)[0].offsetWidth+"px"})}})(jQuery);"use strict";
StackExchange.imageUploader=function(){return{uploadImageDialog:function(l,x){var p="upload-iframe-"+(new Date).getTime();"undefined"===typeof x&&(x="/upload/image");var v="",n=window.FileReader&&window.FormData,q=n&&"ondrop"in window,t=n&&"onpaste"in document.body&&window.Clipboard;q&&t?v="(or paste or drag-and-drop)":q&&(v="(or drag-and-drop)");var s=$('<div class="popup" id="image-upload" style="z-index:1010; width: 420px;" tabindex="-1"><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><iframe id="'+
p+'" style="display:none;" src="about:blank" name="'+p+'"/><form action="'+x+'" id="upload-form" method="post" enctype="multipart/form-data"><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add Image</h2><input type="radio" name="source" id="computer" checked="checked" value="computer" /> <label for="computer">From my computer</label> <input type="file" name="filename" id="filename-input" value="browse" size="18" style="float: right; width: 250px;" /><div id="url-wrapper" style="float: right; border: 0; padding: 0; margin: 0; display: none;"><input type="text" name="upload-url" id="url-input" style="width: 250px;" /><span class="edit-field-overlay">http://example.com/image.png</span></div><br /><input type="radio" name="source" id="web" value="web" /> <label for="web">From the web</label><br /><br /><span style="position: absolute; margin-top: 10px;">'+
v+'</span><input type="submit" id="add-picture" value="Add picture" style="float: right;" /></div><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"></p></form></div><script type="text/javascript">    StackExchange.helpers.bindMovablePopups();    StackExchange.helpers.bindHelpOverlayEvents($("#url-input"));<\/script>'),h,B,y,j=function(a){27===(a.charCode||a.keyCode)&&o(null)},o=function(a){s&&s.fadeOutAndRemove();B&&B.fadeOutAndRemove();$("body").unbind("keydown",j);$("body").unbind("paste");
void 0!==a&&l(a);return!1},C=function(a){o();B=$('<div class="popup" id="image-upload" style="z-index:1010;"><iframe id="'+p+'" style="display:none;" src="about:blank" name="'+p+'"/><div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div><input type="hidden" name="fkey" value="'+StackExchange.options.user.fkey+'" /><div><h2 style="margin-bottom: 12px; cursor: move;" class="handle">Add a picture</h2><img src="'+a+'" style="max-width: 250px;padding: 5px;" /><br /><span style="float: right;"><input type="button" id="confirm-upload" value="Confirm" />&nbsp;&nbsp;&nbsp;<a id="cancel-upload">cancel</a></span><p id="upload-message" style="padding-top: 4px; margin:0; line-height: 16px;"></div></form></div>    <script type="text/javascript">    StackExchange.helpers.bindMovablePopups();<\/script>');
d(B)},k=function(a){a=a||window.event;a.preventDefault&&a.preventDefault();h.style.backgroundColor="white";y=a.dataTransfer.files[0];a=new window.FileReader;a.onloadend=w;a.readAsDataURL(y);return!1},w=function(a){C(a.target.result)},E=function(a){a=a.originalEvent||window.event;if(a.clipboardData&&(a=a.clipboardData.items))for(var b=0;b<a.length;b++)if(-1!==a[b].type.indexOf("image")){y=a[b].getAsFile();var e=(window.URL||window.webkitURL).createObjectURL(y);C(e)}},f=function(){return!1},r=function(){return!1},
a=function(){if(window.FormData){var a=new window.FormData;a.append("uploadedImage",y);a.append("fkey",StackExchange.options.user.fkey);$.ajax({url:x,data:a,cache:!1,contentType:!1,processData:!1,type:"POST",success:function(a){$("#"+p).contents().find("html").html(a)}})}},d=function(){B.appendTo("#header").center().fadeIn("fast");$("body").keydown(j);B.find(".popup-close").click(function(){o(null)});$("#cancel-upload").click(function(){o(null)});$("#confirm-upload").click(a);window.closeDialog=o;
window.displayUploadError=function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a)}};s.appendTo("#header").center().fadeIn("fast").promise().done(function(){h=document.getElementById("image-upload");q&&(h.ondrop=k,h.ondragover=r,h.ondragleave=f);t&&$("body").bind("paste",E);s.find(".popup-close").click(function(){o(null)});s.find(":radio").change(function(){var a=s.find("#filename-input"),b=s.find("#url-wrapper");a.toggle();b.toggle();b.is(":visible")&&s.find("#url-input").focus()});
s.find("form").submit(function(){var a=s.find(":radio:checked").val(),b=s.find("#filename-input"),e=s.find("#url-input"),d;if("web"==a){var g=b[0].parentNode,f=b[0].nextSibling;g.removeChild(b[0]);d=function(){g.insertBefore(b[0],f)}}else g=e[0].parentNode,f=e[0].nextSibling,g.removeChild(e[0]),d=function(){g.insertBefore(e[0],f)};this.target=p;window.closeDialog=o;window.displayUploadError=function(a){$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(a);d();d=null};return!0});
s.find("#filename-input").focus()});$("body").keydown(j);return!0}}}();
StackExchange.postValidation=function(){function l(a,e,c){var d=a.find('input[type="submit"]:visible'),f=d.length&&d.is(":enabled");f&&d.attr("disabled",!0);p(a);v(a,e,c);q(a);t(a);s(a);var h=function(){1!=e||a.find(E).length?(n(a),f&&d.attr("disabled",!1)):setTimeout(h,250)};h()}function x(){for(var a=0;a<d.length;a++)clearTimeout(d[a]);d=[]}function p(a){var e=a.find(k);e.length&&e.blur(function(){d.push(setTimeout(function(){var c=e.val(),d=$.trim(c);if(0==d.length)o(a,e);else{var f=e.data("min-length");
f&&d.length<f?j(e,["Title must be at least "+f+" characters."],h()):(f=e.data("max-length"))&&d.length>f?j(e,["Title cannot be longer than "+f+" characters."],h()):$.ajax({type:"POST",url:"/posts/validate-title",data:{title:c},success:function(c){c.success?o(a,e):j(e,c.errors.Title,h())},error:function(){o(a,e)}})}},c))})}function v(a,e,f){var g=a.find(w);g.length&&g.blur(function(){d.push(setTimeout(function(){var c=g.val(),d=$.trim(c);0==d.length?o(a,g):5==e?(c=g.data("min-length"))&&d.length<c?
j(g,["Wiki Body must be at least "+c+" characters. You entered "+d.length+"."],h()):o(a,g):(1==e||2==e)&&$.ajax({type:"POST",url:"/posts/validate-body",data:{body:c,oldBody:g.prop("defaultValue"),isQuestion:1==e,isSuggestedEdit:f},success:function(e){e.success?o(a,g):j(g,e.errors.Body,h())},error:function(){o(a,g)}})},c))})}function n(a){var e=a.find(E);if(e.length){var f=e.parent().find("input#tagnames");f.blur(function(){d.push(setTimeout(function(){var c=f.val();0==$.trim(c).length?o(a,e):$.ajax({type:"POST",
url:"/posts/validate-tags",data:{tags:c,oldTags:f.prop("defaultValue")},success:function(c){c.success?o(a,e):j(e,c.errors.Tags,h())},error:function(){o(a,e)}})},c))})}}function q(a){var e=a.find(f);e.length&&e.blur(function(){d.push(setTimeout(function(){var c=e.val(),c=$.trim(c);if(0==c.length)o(a,e);else{var d=e.data("min-length");d&&c.length<d?j(e,["Your edit summary must be at least "+d+" characters."],h()):(d=e.data("max-length"))&&c.length>d?j(e,["Your edit summary cannot be longer than "+d+
" characters."],h()):o(a,e)}},c))})}function t(a){var e=a.find(r);e.length&&e.blur(function(){d.push(setTimeout(function(){var c=e.val(),c=$.trim(c);if(0==c.length)o(a,e);else{var d=e.data("min-length");d&&c.length<d?j(e,["Wiki Excerpt must be at least "+d+" characters; you entered "+c.length+"."],h()):(d=e.data("max-length"))&&c.length>d?j(e,["Wiki Excerpt cannot be longer than "+d+" characters; you entered "+c.length+"."],h()):o(a,e)}},c))})}function s(b){var e=b.find(a);e.length&&e.blur(function(){d.push(setTimeout(function(){var a=
e.val();0==$.trim(a).length?o(b,e):/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,20}$/i.test(a)?o(b,e):j(e,["This email does not appear to be valid."],B())},c))})}function h(){var a=$("#sidebar, .sidebar").first().width()||270;return{position:{my:"left top",at:"right center"},css:{"max-width":a,"min-width":a},closeOthers:!1}}function B(){return{position:{my:"left top",at:"right center"},css:{"min-width":$("#sidebar, .sidebar").first().width()||270},closeOthers:!1}}function y(b,c,d,g){if(b){var l=function(){var d=
0;j(c.find(k),b.Title,h())?d++:o(c,c.find(k));j(c.find(w),b.Body,h())?d++:o(c,c.find(w));j(c.find(E),b.Tags,h())?d++:o(c,c.find(E));j(c.find(f),b.EditComment,h())?d++:o(c,c.find(f));j(c.find(r),b.Excerpt,h())?d++:o(c,c.find(r));j(c.find(a),b.Email,B())?d++:o(c,c.find(a));var i=c.find(".general-error"),l=b.General&&0<b.General.length;l||0<d?(i.length||(c.find('input[type="submit"]:visible').before('<div class="general-error-container"><div class="general-error"></div><br class="cbt" /></div>'),i=c.find(".general-error")),
l?j(i,b.General,{position:"inline",css:{"float":"left","margin-bottom":"10px"},closeOthers:!1,dismissable:!1}):(o(c,i),i.text("Your "+g+" couldn't be submitted. Please see the "+(1==d?"error":"errors")+" above."))):c.find(".general-error-container").remove();var n;C()&&($("#sidebar").animate({opacity:0.4},500),n=setInterval(function(){C()||($("#sidebar").animate({opacity:1},500),clearInterval(n))},500));var p;c.find(".validation-error").each(function(){var a=$(this).offset().top;if(!p||a<p)p=a});
d=function(){};p&&(i=$(".review-bar").length,p=Math.max(0,p-(i?125:30)),$("html, body").animate({scrollTop:p},d))},n=function(){1!=d||c.find(E).length?l():setTimeout(n,250)};n()}}function j(a,c,d){if(!c||0==c.length||!a.length)return!1;if((c=1==c.length?c[0]:"<ul><li>"+c.join("</li><li>")+"</li></ul>")&&0<c.length){var f=a.data("error-popup");if(f&&f.is(":visible")){if(a.data("error-message")==c)return!0;f.fadeOutAndRemove()}d=StackExchange.helpers.showMessage(a,c,d);d.find("a").attr("target","_blank");
a.addClass("validation-error");a.data("error-popup",d);a.data("error-message",c);d.click(x);return!0}return!1}function o(a,c){if(!c||0==c.length)return!1;var d=c.data("error-popup");d&&d.is(":visible")&&d.fadeOutAndRemove();c.removeClass("validation-error");c.removeData("error-popup");c.removeData("error-message");a.find(".validation-error").length||a.find(".general-error-container").remove();return!0}function C(){var a=!1,c=$("#sidebar, .sidebar").first();if(!c.length)return!1;var d=c.offset().left;
$(".message").each(function(){var c=$(this);if(c.offset().left+c.outerWidth()>d)return a=!0,!1});return a}var k="input#title",w="textarea.wmd-input:first",E=".tag-editor",f="input[id^=edit-comment]",r="textarea#excerpt",a="input#m-address",d=[],c=250;return{initOnBlur:l,initOnBlurAndSubmit:function(a,c,d,f,h){l(a,c,f);var j,k=function(f){if(f.success)if(h)h(f);else{var g=window.location.href.split("#")[0],l=f.redirectTo.split("#")[0];0==l.indexOf("/")&&(l=window.location.protocol+"//"+window.location.hostname+
l);j=!0;window.location=f.redirectTo;g.toLowerCase()==l.toLowerCase()&&window.location.reload(!0)}else f.captchaHtml?StackExchange.captcha.init(f.captchaHtml,k):f.errors?y(f.errors,a,c,d):a.find('input[type="submit"]:visible').parent().showErrorMessage(f.message)};a.submit(function(){if(a.find("#answer-from-ask").is(":checked"))return!0;x();StackExchange.navPrevention&&StackExchange.navPrevention.stop();a.find('input[type="submit"]:visible').parent().addSpinner();StackExchange.helpers.disableSubmitButton(a);
setTimeout(function(){$.ajax({type:"POST",dataType:"json",data:a.serialize(),url:a.attr("action"),success:k,error:function(){a.find('input[type="submit"]:visible').parent().showErrorMessage("An error occurred submitting the "+d+".")},complete:function(){StackExchange.helpers.removeSpinner();j||StackExchange.helpers.enableSubmitButton(a)}})},0);return!1})},showErrorsAfterSubmission:y,getSidebarPopupOptions:h}}();
